#!/bin/bash

# if a directory argument is passed, set the directory variable to its absolute path
directory=$( [[ $1 ]] && echo "$HOME/$1")

movies_path=$HOME/movies
pictures_path=$HOME/pictures
docs_path=$HOME/documents
music_path=$HOME/music
downloads_path=$HOME/downloads
desktop_path=$HOME/desktop

destination_paths=($movies_path $pictures_path $docs_path $music_path $downloads_path $desktop_path)

move(){
  extensions=$1
  source_directory="$2"

  if [[ $source_directory && ! -d $source_directory ]]; then
    echo $source_directory does not exist, pass a directory relative to the '$HOME' directory >&2
    exit 1
  fi

  for file_type in $extensions; do
    case $file_type in
      videos)
        destination=$movies_path
        extensions="(mkv|avi|mov|mpeg|mp4)" ;;
      audios)
        destination=$music_path
        extensions="(mp3|m4a)" ;;
      docs)
        destination=$docs_path
        extensions="(pdf|txt|docx|xls|csv)" ;;
      images)
        destination=$pictures_path
        extensions="(jpg|png|jpeg)" ;;
    esac

    if [[ $source_directory ]]; then
      source_dir=$source_directory
    else
      source_dir=${destination_paths[@]/$destination}
    fi
    find -E $source_dir -regex ".*.$extensions" -maxdepth 1 -exec mv '{}' $destination \;
  done
}

move "videos audios docs images" $directory